
DROP TABLE IF EXISTS BATCH_PROCESSING_FILE;

DROP TABLE IF EXISTS IMAGE_BATCH;

--------------

create table BATCH_PROCESSING_FILE (BPF_ID bigint generated by default as identity, BPF_NAME varchar(255), BPF_CREATED date, BPF_FINISHED date, primary key (BPF_ID));

create table IMAGE_BATCH (IMG_ID bigint generated by default as identity, IMG_NAME varchar(255), BPF_ID bigint, IMG_CONVERSION varchar(255), IMG_CREATED date, primary key (IMG_ID));

-- alter table IMAGE_TYPE add constraint UK_IMT_EXTENSION unique (IMT_EXTENSION);

-- alter table IMAGE_CONVERTION add constraint FK_IMT_IMGC foreign key (IMT_ID) references IMAGE_TYPE;